version: '3.1'
services:
  web:
    container_name: Harsh
    environment:
      CSVSERVER_BORDER: Orange
    image: infracloudio/csvserver:latest
    ports:
    - 9300:9300
    volumes:
    - /home/ubuntu/mainfolder/inputfile:/csvserver/inputdata
  prometheus:
    image: prom/prometheus:v2.22.0
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
    - "9090:9090"
